modLoader="javafml" #mandatory
loaderVersion="[46,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
issueTrackerURL="https://github.com/TheBreadMan0/RainbowDye/issues" #optional
[[mods]] #mandatory
modId="rainbowdye" #mandatory
version="1.0.0-1.20.1" #mandatory
displayName="Rainbow Dye" #mandatory
logoFile="logo.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="TheBreadMan" #optional
description='''
Rainbow Dye is a mod for Minecraft that adds a new dye to the game that can be used in crafting recipes.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.rainbowdye]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[46,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.rainbowdye]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"